name: 'Automatic Version Bumper'
description: 'Automatically bumps version and creates releases based on PR title conventions'
inputs:
  token:
    description: 'GitHub token for creating releases'
    required: true
  initial_version:
    description: 'Initial version to start from (from secrets)'
    required: true
  draft:
    description: 'Create release as draft'
    required: false
    default: 'false'
  prerelease:
    description: 'Mark as prerelease'
    required: false
    default: 'false'
outputs:
  new_version:
    description: 'The new version number'
    value: ${{ env.NEW_VERSION }}

runs:
  using: 'composite'
  steps:
    - name: Setup initial version
      shell: bash
      run: |
        echo "INITIAL_VERSION=${{ inputs.initial_version }}" >> $GITHUB_ENV
        echo "Initial version set to: ${{ inputs.initial_version }}"

    - name: Get current version
      shell: bash
      id: get-version
      run: |
        echo "Fetching tags..."
        git fetch --tags --force
        
        # Try to get the latest tag
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        echo "Latest git tag found: ${LATEST_TAG}"
        
        # If no tag exists, use initial version
        if [ -z "$LATEST_TAG" ]; then
          echo "No existing tags found, using initial version: $INITIAL_VERSION"
          echo "CURRENT_VERSION=$INITIAL_VERSION" >> $GITHUB_ENV
        else
          # Remove 'v' prefix if it exists
          CURRENT_VERSION=${LATEST_TAG#v}
          echo "Using existing version: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
        fi

    - name: Determine version bump
      shell: bash
      id: version-bump
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        echo "Processing PR title: $PR_TITLE"
        
        # First check for breaking changes
        if [[ $PR_TITLE =~ ^feat!: || $PR_TITLE =~ ^fix!: || $PR_TITLE =~ ^BREAKING[[:space:]]CHANGE ]]; then
          echo "BUMP=major" >> $GITHUB_ENV
          echo "Determined MAJOR version bump"
        # Then check for features
        elif [[ $PR_TITLE =~ ^feat: ]]; then
          echo "BUMP=minor" >> $GITHUB_ENV
          echo "Determined MINOR version bump"
        # Then check for fixes
        elif [[ $PR_TITLE =~ ^fix: ]]; then
          echo "BUMP=patch" >> $GITHUB_ENV
          echo "Determined PATCH version bump"
        else
          echo "BUMP=none" >> $GITHUB_ENV
          echo "No version bump needed"
        fi

    - name: Calculate new version
      if: env.BUMP != 'none'
      shell: bash
      id: calc-version
      run: |
        echo "Current version: $CURRENT_VERSION"
        
        # Split version into major, minor, patch
        IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
        
        # Calculate new version
        case $BUMP in
          major)
            NEW_VERSION="$((MAJOR + 1)).0.0"
            ;;
          minor)
            NEW_VERSION="${MAJOR}.$((MINOR + 1)).0"
            ;;
          patch)
            NEW_VERSION="${MAJOR}.${MINOR}.$((PATCH + 1))"
            ;;
        esac
        
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        echo "Calculated new version: $NEW_VERSION"

    - name: Create and push tag
      if: env.BUMP != 'none' && env.NEW_VERSION != ''
      shell: bash
      run: |
        # Configure git
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        echo "Creating new tag v$NEW_VERSION..."
        git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"
        
        echo "Pushing tag to repository..."
        git push origin "v$NEW_VERSION" --force
