name: 'Automatic Version Bumper'
description: 'Automatically bumps version, updates changelog, and creates releases based on PR title conventions'
inputs:
  token:
    description: 'GitHub token for creating releases'
    required: true
    default: ${{ github.token }}
  draft:
    description: 'Create release as draft'
    required: false
    default: 'false'
  prerelease:
    description: 'Mark as prerelease'
    required: false
    default: 'false'
  changelog_path:
    description: 'Path to the CHANGELOG.md file'
    required: false
    default: 'CHANGELOG.md'

runs:
  using: 'composite'
  steps:
    - name: Get version from package.json
      shell: bash
      id: package-version
      run: |
        if [ -f package.json ]; then
          VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=v${VERSION}" >> $GITHUB_ENV
        fi
      continue-on-error: true

    - name: Get version from .version file
      shell: bash
      id: version-file
      run: |
        if [ -f .version ]; then
          VERSION=$(cat .version)
          echo "FILE_VERSION=v${VERSION}" >> $GITHUB_ENV
        fi
      continue-on-error: true

    - name: Get latest tag
      shell: bash
      id: get-latest-tag
      run: |
        git fetch --tags
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        # Priority order: git tag > package.json > .version file > default
        if [ ! -z "$LATEST_TAG" ]; then
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
        elif [ ! -z "$PACKAGE_VERSION" ]; then
          echo "LATEST_TAG=$PACKAGE_VERSION" >> $GITHUB_ENV
        elif [ ! -z "$FILE_VERSION" ]; then
          echo "LATEST_TAG=$FILE_VERSION" >> $GITHUB_ENV
        else
          echo "LATEST_TAG=v0.0.0" >> $GITHUB_ENV
        fi

    - name: Determine version bump
      shell: bash
      id: version-bump
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        if [[ $PR_TITLE =~ ^feat!: || $PR_TITLE =~ ^fix!: || $PR_TITLE =~ ^BREAKING[[:space:]]CHANGE ]]; then
          echo "BUMP=major" >> $GITHUB_ENV
        elif [[ $PR_TITLE =~ ^feat: ]]; then
          echo "BUMP=minor" >> $GITHUB_ENV
        elif [[ $PR_TITLE =~ ^fix: ]]; then
          echo "BUMP=patch" >> $GITHUB_ENV
        else
          echo "BUMP=none" >> $GITHUB_ENV
        fi
        echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV

    - name: Bump version
      if: env.BUMP != 'none'
      shell: bash
      id: bump-version
      run: |
        CURRENT_VERSION=${LATEST_TAG#v}
        IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
        case $BUMP in
          major)
            NEW_VERSION="$((MAJOR + 1)).0.0"
            ;;
          minor)
            NEW_VERSION="${MAJOR}.$((MINOR + 1)).0"
            ;;
          patch)
            NEW_VERSION="${MAJOR}.${MINOR}.$((PATCH + 1))"
            ;;
        esac
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        echo "New version: v$NEW_VERSION"

    - name: Update CHANGELOG.md
      if: env.BUMP != 'none' && env.NEW_VERSION != ''
      shell: bash
      run: |
        CHANGELOG_FILE="${{ inputs.changelog_path }}"
        DATE=$(date +%Y-%m-%d)
        
        # Create changelog if it doesn't exist
        if [ ! -f "$CHANGELOG_FILE" ]; then
          echo "# Changelog" > "$CHANGELOG_FILE"
          echo "" >> "$CHANGELOG_FILE"
        fi
        
        # Prepare new changelog entry
        TEMP_FILE=$(mktemp)
        {
          head -n 1 "$CHANGELOG_FILE"
          echo ""
          echo "## [v${{ env.NEW_VERSION }}] - $DATE"
          echo ""
          echo "### Changes"
          echo "- ${PR_TITLE} (#${{ github.event.pull_request.number }})"
          echo ""
          tail -n +2 "$CHANGELOG_FILE"
        } > "$TEMP_FILE"
        mv "$TEMP_FILE" "$CHANGELOG_FILE"
        
        # Stage and commit changelog
        git add "$CHANGELOG_FILE"
        git commit -m "docs: update changelog for v${{ env.NEW_VERSION }}"

    - name: Create and push tag
      if: env.BUMP != 'none' && env.NEW_VERSION != ''
      shell: bash
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"
        git push origin HEAD:${{ github.event.pull_request.base.ref }} --tags

    - name: Extract release notes from changelog
      if: env.BUMP != 'none' && env.NEW_VERSION != ''
      shell: bash
      id: extract-notes
      run: |
        CHANGELOG_FILE="${{ inputs.changelog_path }}"
        VERSION_HEADER="## [v${{ env.NEW_VERSION }}]"
        RELEASE_NOTES=$(awk -v ver="$VERSION_HEADER" '
          $0 ~ ver {p=1;next}
          /^## / {p=0}
          p {print}
        ' "$CHANGELOG_FILE" | sed '/^$/d')
        echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
        echo "$RELEASE_NOTES" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Create Release
      if: env.BUMP != 'none' && env.NEW_VERSION != ''
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        tag_name: v${{ env.NEW_VERSION }}
        release_name: Release v${{ env.NEW_VERSION }}
        body: ${{ env.RELEASE_NOTES }}
        draft: ${{ inputs.draft }}
        prerelease: ${{ inputs.prerelease }}
